CREATE TABLE [dbo].[ViewSubscribedContacts-CowboysMaster_20180110_104441]
(
[Email] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscribe Date (UTC-06)] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Method] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModalA_Hybrid_Source] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ModalB_Normal_Source] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Modal_Source] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Account_Source] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Checkout_Source] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PrefCenter_Source] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Miniform_Source] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProShop] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OfficialSite] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VIP] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewModalA_Hybrid] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewModalB_Normal] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewModal] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GuestCheckout] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailToken] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZipCode] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DefaultBirthMonth] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BirthDay] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BirthMonth] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BirthYear] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenderMale] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GenderFemale] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FavoritePlayer] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Is18orOlder] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JKTempFlag] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceSheet] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
