CREATE TABLE [dbo].[ViewSubscribedContacts-CowboysMaster_20180110_104802]
(
[Email] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscribe Date (UTC-06)] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Method] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DCUnitedMembershipType] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalesRepName] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalesRepEmailAddress] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalesRepPhone] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServiceRepName] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServiceRepEmailAddress] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServiceRepPhone] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewFoundEmail] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NewFoundEmailSegment] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DCUnitedRefreshDate] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STHSuiteRefreshDate] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CSNotify] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Coupon] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CSReason] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerFlag] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrderCount] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AvgReorderDays] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstOrderDate] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastOrderDate] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProjectedOrderDate] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpentOneYear] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpentTwoYear] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpentThreeYear] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SpentTotal] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecentItemsPurchased] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecentItemsPurchasedOverflow] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AverageOrderValue] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PurchaseSources] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceSheet] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
