CREATE TABLE [dbo].[ViewSubscribedContacts-CowboysMaster_20180110_104622]
(
[Email] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscribe Date (UTC-06)] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Method] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FreshAddressScore] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateCode] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FanManagerSegmentationTag] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LDTempFlag] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OSTempFlag] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EnteredWelcomeSeries] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WelcomeSeriesReceived] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CouponCode] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CouponExpiration] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OfficialSiteReceived] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StadiumEventsReceived] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StarInFriscoReceived] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DCProShopOffers] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DCNewsletter] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DCFanPlaybook] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DCEventsAndTicketOffers] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTStadiumEventsAndTicketOffers] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FordCenterEventsAndTicketOffers] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DCSeasonTicketHolder] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ATTStadiumSuiteHolder] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DCUnitedMember] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DCCorporatePartner] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FivePointsBlue] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StadiumClub] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TheStarTours] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CowboysClub] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CowboysFit] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TheStarInformationAndNotifications] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TheStar] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SourceSheet] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
