CREATE TABLE [ods].[SGDW_FactSubscriptionInstances]
(
[fsiLocalId] [int] NOT NULL,
[fsiGuid] [uniqueidentifier] NOT NULL,
[fsiHolderCompanyId] [int] NOT NULL,
[fsiCreateDate] [datetime] NOT NULL,
[fsiMasterInstanceCreateDate] [datetime] NULL,
[fsiSubscriptionGuid] [uniqueidentifier] NOT NULL,
[fsiStatus] [int] NOT NULL,
[fsiRenewStatus] [int] NOT NULL,
[fsiClientGuid] [uniqueidentifier] NOT NULL,
[fsiPurchaserGuid] [uniqueidentifier] NULL,
[fsiRenewOfInstanceGuid] [uniqueidentifier] NULL,
[fsiUpdateOfInstanceGuid] [uniqueidentifier] NULL,
[fsiMasterInstanceGuid] [uniqueidentifier] NULL,
[fsiSeasonGuid] [uniqueidentifier] NULL,
[fsiSeriesGuid] [uniqueidentifier] NOT NULL,
[fsiSeriesGroupGuid] [uniqueidentifier] NULL,
[fsiStartDate] [datetime] NULL,
[fsiEndDate] [datetime] NULL,
[fsiEventCount] [int] NOT NULL,
[fsiBonusEventCount] [int] NOT NULL,
[fsiPriceTypeGuid] [uniqueidentifier] NOT NULL,
[fsiPriceLevelGuid] [uniqueidentifier] NULL,
[fsiHallGuid] [uniqueidentifier] NULL,
[fsiAreaGuid] [uniqueidentifier] NULL,
[fsiSeatIdInAreaMap] [int] NULL,
[fsiIsGa] [bit] NULL,
[fsiRestrictionGuid] [uniqueidentifier] NULL,
[fsiTransactionGuid] [uniqueidentifier] NULL,
[fsiTransactNum] [int] NULL,
[fsiApplicationChannel] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fsiNote] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fsiIsGift] [bit] NOT NULL,
[fsiSingleEventPrice] [money] NULL,
[fsiSingleBonusEventPrice] [money] NULL,
[fsiIsCurrent] [bit] NULL,
[fsiRegularTicketsUtilization] [int] NULL,
[fsiBonusTicketsUtilization] [int] NULL,
[fsiPrintCount] [int] NOT NULL,
[fsiWaitModeEnum] [int] NULL,
[fsiPrintedNumber] [int] NULL,
[fsiSubsidizedByAccountGuid] [uniqueidentifier] NULL,
[fsiBarcode] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fsiIsAutoRenew] [bit] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_ods__SGDW_FactSubscriptionInstances] ON [ods].[SGDW_FactSubscriptionInstances]
GO
