CREATE TABLE [ods].[SGDW_FactPaymentSessions]
(
[fpsLocalId] [int] NOT NULL,
[fpsHolderCompanyId] [int] NOT NULL,
[fpsId] [uniqueidentifier] NOT NULL,
[fpsLocalRefNumber] [bigint] NOT NULL,
[fpsResultRefNumber] [nvarchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fpsStartDate] [datetime] NOT NULL,
[fpsEndDate] [datetime] NULL,
[fpsOperationEnum] [int] NOT NULL,
[fpsPaymentMethodId] [uniqueidentifier] NULL,
[fpsCompletionCodeEnum] [int] NULL,
[fpsClientId] [uniqueidentifier] NULL,
[fpsPaymentItemId] [uniqueidentifier] NULL,
[fpsTransactionId] [uniqueidentifier] NULL,
[fpsResultConfirmationNumber] [nvarchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fpsResultClearingCompany] [nvarchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fpsResultCardType] [nvarchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fpsResultCardSuffix] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fpsResultCardToken] [nvarchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fpsResultCardNumberMask] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fpsResultExtraData] [xml] NULL,
[fpsComments] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fpsApplicationChannel] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[fpsResultCardHolderName] [nvarchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fpsResultBillingAddress] [nvarchar] (254) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fpsResultClearingCompanyId] [uniqueidentifier] NULL,
[fpsResultCardCompanyId] [uniqueidentifier] NULL,
[fpsResultCardExpirationMM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fpsResultCardExpirationYY] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fpsResultCardPrefix] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
