CREATE TABLE [ods].[SGDW_FactSubscriptions]
(
[fsLocalId] [int] NOT NULL,
[fsItemGuid] [uniqueidentifier] NOT NULL,
[fsHolderCompanyId] [int] NOT NULL,
[fsIssuerCompanyId] [int] NULL,
[fsStiGuid] [uniqueidentifier] NOT NULL,
[fsTransactionGuid] [uniqueidentifier] NULL,
[fsTransactNum] [int] NULL,
[fsClientGuid] [uniqueidentifier] NULL,
[fsSubscriptionGuid] [uniqueidentifier] NULL,
[fsSubscriptionInstanceGuid] [uniqueidentifier] NULL,
[fsActualDate] [datetime] NULL,
[fsBusinessDate] [datetime] NULL,
[fsForwardTranGuid] [uniqueidentifier] NULL,
[fsBackwardTranGuid] [uniqueidentifier] NULL,
[fsPrice] [money] NULL,
[fsActionSign] [bit] NOT NULL,
[fsStatusAction] [int] NULL,
[fsTotalTax] [money] NULL,
[fsTotalTaxIncluded] [money] NULL,
[fsTotalVat] [money] NULL,
[fsTotalVatIncluded] [money] NULL,
[fsTotalCommission] [money] NULL,
[fsTotalDiscount] [money] NULL,
[fsPriceTypeGuid] [uniqueidentifier] NULL,
[fsPriceLevelGuid] [uniqueidentifier] NULL,
[fsSalePointGuid] [uniqueidentifier] NULL,
[fsShiftGuid] [uniqueidentifier] NULL,
[fsTillGuid] [uniqueidentifier] NULL,
[fsUserGuid] [uniqueidentifier] NULL,
[fsSaleModeGuid] [uniqueidentifier] NULL,
[fsApplicationChannel] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fsBusinessCategoryGuid] [uniqueidentifier] NULL,
[fsOnBehalfOfAccountGuid] [uniqueidentifier] NULL,
[fsIsAccount] [bit] NULL,
[fsIsReserved] [bit] NULL,
[fsIsComplimentary] [bit] NULL,
[fsConfirmationDate] [datetime] NULL,
[fsRelCommission] [money] NULL,
[fsIsPrinted] [bit] NULL,
[fsSellerBranchGuid] [uniqueidentifier] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_ods__SGDW_FactSubscriptions] ON [ods].[SGDW_FactSubscriptions]
GO
