CREATE TABLE [ods].[SGDW_DimShows]
(
[dshLocalId] [int] NOT NULL,
[dshHolderCompanyId] [int] NOT NULL,
[dshIssuerCompanyId] [int] NOT NULL,
[dshGuid] [uniqueidentifier] NOT NULL,
[dshName] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dshShowTypeGuid] [uniqueidentifier] NULL,
[dshOwnerGuid] [uniqueidentifier] NULL,
[dshLedgerGuid] [uniqueidentifier] NULL,
[dshProjectIdentifierGuid] [uniqueidentifier] NULL,
[dshExtendedData1] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dshExtendedData2] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dshExtendedData3] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dshExtendedData4] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dshExtendedData5] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dshExtendedData6] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dshExtendedData7] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dshExtendedData8] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dshExtendedData9] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dshExtendedData10] [datetime] NULL,
[dshExtendedData11] [datetime] NULL,
[dshExtendedData12] [datetime] NULL,
[dshExtendedData13] [datetime] NULL,
[dshExtendedData14] [datetime] NULL,
[dshProducerGuid] [uniqueidentifier] NULL,
[dshIsActive] [bit] NOT NULL,
[dshSalesTargetValue] [money] NULL,
[dshShowPromoterGuid] [uniqueidentifier] NULL,
[dshShowOrganizerGuid] [uniqueidentifier] NULL,
[dshOrganizationUnitGuid] [uniqueidentifier] NULL,
[dshPromoterPriceListIdForRegularTickets] [uniqueidentifier] NULL,
[dshPromoterPriceListIdForSubsTickets] [uniqueidentifier] NULL,
[dshAclSchemeId] [int] NULL,
[dshRemark] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dshVisibleBySubordinates] [bit] NOT NULL,
[dshShowMinutes] [int] NULL,
[dshBreakMinutes] [int] NULL,
[dshCalcPotentialPriceListId] [uniqueidentifier] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
CREATE CLUSTERED COLUMNSTORE INDEX [CCI_ods__SGDW_DimShows] ON [ods].[SGDW_DimShows]
GO
