CREATE TABLE [seat].[FILE__ssb_stadium_20180226_FP_note]
(
[ETL__ID] [bigint] NOT NULL IDENTITY(1, 1),
[ETL__CreatedDate] [datetime] NOT NULL,
[ETL__Source] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ETL__DeltaHashKey] [binary] (32) NULL,
[note_id] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[acct_id] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[note_type] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[priority] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEXT] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[reminder_id] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[category_code] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[category] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[subcategory_code] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[subject] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[response_code] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[response] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contact_type_code] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[contact_type] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_status_code] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_status] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[alert_id] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[alert_name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[icon_file_name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[owner_user_id] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[email_owner_on_chg] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[duration] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[solicitation_id] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[solicitation_name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[location] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[label] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[start_datetime] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[end_datetime] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[all_day_event] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[show_time_as] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[added_to_outlook] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[add_user] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[add_datetime] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[upd_user] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[upd_datetime] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_type_code] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_type] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[assigned_to_user_id] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_stage_seq_num] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_activity_code] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_result_code] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_stage_status_code] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_activity] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_result] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_stage_status] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_assigned_to_user_id] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_assigned_to_dept_id] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_dept_name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_assignee_notified] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_duration] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_stage_text] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_start_date] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_end_date] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_probability_to_close] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[task_probability_to_close_name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[org_id] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[org_name] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TeamName] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[action] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[export_datetime] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[seq_num] [nvarchar] (2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [seat].[FILE__ssb_stadium_20180226_FP_note] ADD CONSTRAINT [PK__FILE__ss__C4EA24453A7058F7] PRIMARY KEY CLUSTERED  ([ETL__ID])
GO
