CREATE TABLE [src].[Listrak_SubscribedContacts_FACustomerMetrics]
(
[Email] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subscribe Date (UTC-06)] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Method] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Customer Flag] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Order Count] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Avg Reorder Days] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics First Order Date] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Last Order Date] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Projected Order Date] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Spent One Year] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Spent Two Year] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Spent Three Year] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Spent Total] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Recent Items Purchased] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Recent Items Purchased Overflow] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Gender] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Average Order Value] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Purchase Sources] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Last Browsed Brand] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Last Browsed Category] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Last Browsed Subcategory] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Last Site Visit] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Most Browsed Brand] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Most Browsed Category] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Most Browsed Subcategory] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Recent Items Browsed] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FA Customer Metrics Recent Items Browsed Overflow] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
