CREATE TABLE [stg].[Sync_temp_ods_SGDW_FactItems]
(
[fiLocalId] [int] NOT NULL,
[fiHolderCompanyId] [int] NOT NULL,
[fiTransactionLocalId] [int] NOT NULL,
[fiIdInTransaction] [int] NOT NULL,
[fiTypeNumber] [int] NOT NULL,
[fiRetailerCompanyId] [int] NULL,
[fiForwardTransactionGuid] [uniqueidentifier] NULL,
[fiIdInForwardTransaction] [int] NULL,
[fiDeliveryItemId] [uniqueidentifier] NULL,
[fiReservationExpiryDate] [datetime] NULL,
[fiExtraFields] [xml] NULL,
[fiBackwardTransactionGuid] [uniqueidentifier] NULL,
[fiIdInBackwardTransaction] [int] NULL,
[fiIsComplimentary] [bit] NULL,
[fiGuid] [uniqueidentifier] NOT NULL,
[fiAssociatedClientId] [uniqueidentifier] NULL,
[fiOriginalServiceSpecificId] [uniqueidentifier] NULL,
[fiProductInstanceId] [uniqueidentifier] NULL,
[fiPriceTypeId] [uniqueidentifier] NULL,
[fiIsFictivePayment] [bit] NULL,
[fiPriceEffectivenessEnum] [int] NULL,
[fiECardId] [uniqueidentifier] NULL,
[fiOriginalPriceTypeId] [uniqueidentifier] NULL,
[fiSubsidizedByAccountId] [uniqueidentifier] NULL,
[fiTransactIssuerCompanyId] [int] NULL,
[fiTransactNum] [int] NULL,
[fiTransactionGuid] [uniqueidentifier] NULL,
[fiListPrice] [money] NULL,
[fiItemPrice] [money] NULL,
[fiActionSign] [smallint] NULL,
[fiIsReserved] [bit] NULL,
[fiShiftGuid] [uniqueidentifier] NULL,
[fiIsAccount] [bit] NULL,
[fiSalePointGuid] [uniqueidentifier] NULL,
[fiUserGuid] [uniqueidentifier] NULL,
[fiTillGuid] [uniqueidentifier] NULL,
[fiClientGuid] [uniqueidentifier] NULL,
[fiRecoAccountId] [uniqueidentifier] NULL,
[fiActualDate] [datetime] NULL,
[fiBusinessDate] [datetime] NULL,
[fiApplicationChannel] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fiSaleModeId] [uniqueidentifier] NULL,
[fiBusinessCategory] [uniqueidentifier] NULL,
[fiConfirmationDate] [datetime] NULL,
[fiOnBehalfOfAccountId] [uniqueidentifier] NULL,
[fiRelationName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fiRelatedItemGuid] [uniqueidentifier] NULL,
[fiTransactionNote] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[fiRequestedActionEnum] [int] NULL,
[fiTotalCommissionIncluded] [money] NULL,
[fiTotalTax] [money] NULL,
[fiTotalTaxIncluded] [money] NULL,
[fiTotalVat] [money] NULL,
[fiTotalVatIncluded] [money] NULL,
[fiTotalCommission] [money] NULL,
[fiTotalDiscount] [money] NULL,
[fiItemPriceAfterDiscount] [money] NULL,
[fiTotalExtraCharge] [money] NULL,
[fiIsValid] [bit] NULL,
[fiEntityGuid] [uniqueidentifier] NULL,
[fiPaymentId] [uniqueidentifier] NULL,
[fiPaymentSubType] [uniqueidentifier] NULL,
[fiRelCommision] [money] NULL,
[fiPaymentMethod] [uniqueidentifier] NULL,
[fiCouponItemId] [uniqueidentifier] NULL,
[fiCouponDefinitionId] [uniqueidentifier] NULL,
[fiUserOfAffiliateAccountGuid] [uniqueidentifier] NULL,
[fiAgencyAccountGuid] [uniqueidentifier] NULL,
[fiSupplierGuid] [uniqueidentifier] NULL,
[fiSupplierBranchGuid] [uniqueidentifier] NULL,
[fiSellerBranchGuid] [uniqueidentifier] NULL,
[fiIsModifiedReservation] [bit] NULL,
[fiTickSeries] [uniqueidentifier] NULL,
[fiEventGuid] [uniqueidentifier] NULL,
[fiGroupOrderGuid] [uniqueidentifier] NULL,
[fiGroupOrderId] [int] NULL,
[fiPrintCount] [int] NULL,
[fiLinkingProductTypeId] [int] NULL,
[fiLinkingProductGuid] [uniqueidentifier] NULL,
[fiIsExtraProduct] [bit] NULL,
[fiPartOfPromptGuid] [uniqueidentifier] NULL,
[fiAssociatedWithBenefit] [bit] NULL,
[fiBenefitMembershipGuid] [uniqueidentifier] NULL,
[fiBenefitPackageElementGuid] [uniqueidentifier] NULL,
[fiSalesRepresentativeId] [uniqueidentifier] NULL,
[fiRegularPrice] [money] NULL,
[fiTotalPrice] [money] NULL,
[fiPaidPrice] [money] NULL,
[fiCommissionsAmount] [money] NULL,
[fiTaxAmount] [money] NULL,
[fiPaidByItemIdInTransaction] [int] NULL,
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [stg].[Sync_temp_ods_SGDW_FactItems] ADD CONSTRAINT [PK__Sync_tem__19364FD2DC21B9A0] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
