CREATE TABLE [stg].[view_tab_Sales]
(
[dim_Sales_Order_key] [int] NOT NULL,
[Sales_Order_Data_Area_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Order_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Purchase_Order_Form_Number] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_Invoice_key] [int] NOT NULL,
[Invoice_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_Picking_List_key] [int] NOT NULL,
[Picking_List_ID] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_Item_key] [int] NOT NULL,
[Item_Data_Area_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Item_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Color_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Size_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Config_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Product_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Item_Name] [nvarchar] (62) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary_Vendor] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Color] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Size] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Configuration] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Harmonized_Code] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Net_Weight] [float] NULL,
[Height] [float] NULL,
[Width] [float] NULL,
[Depth] [float] NULL,
[Unit_Volume] [float] NULL,
[Department] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department_Group] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sub_Department] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Class] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sub_Class] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Season_Code] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Brand_Group] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Style] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Item_Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Graphics_Code] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MSRP] [money] NULL,
[First_Available_Date] [date] NULL,
[Sizing_Scale] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country_Of_Origin] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Product_Line] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Bar_Code] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Size_Order] [int] NULL,
[Available_Date] [date] NULL,
[Retail_Price] [numeric] (32, 16) NULL,
[Wholesale_Price] [numeric] (32, 16) NULL,
[At_Risk_Item_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Over_Sold_Item_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Daly_Item_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Daly_Item_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Counting_Group_ID] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Counting_Group_Name] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_Order_Customer_key] [int] NOT NULL,
[Order_Account_Num] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Data_Area_ID] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Phone] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Customer_Group] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Sales_Rep] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Sales_Agency] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Customer_Classification_Group] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Price_Group] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Email_Address] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Cust_Address] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Street_Name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Street_Num] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_PO_Box] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_City] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_County] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_State_Code] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Postal_Code] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Country_Code] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Latitude] [numeric] (32, 16) NULL,
[Order_Cust_Longitude] [numeric] (32, 16) NULL,
[Order_Cust_Tax_Group_Name] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Payment_Mode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Credit_Rating] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Daly_Customer_Number] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Daly_Company_Number] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Order_Cust_Daly_Flag] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dim_Invoice_Customer_key] [int] NOT NULL,
[Invoice_Account_Num] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Data_Area_ID] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Phone] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Customer_Group] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Sales_Rep] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Sales_Agency] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Customer_Classification_Group] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Price_Group] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Email_Address] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invc_Cust_Address] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Street_Name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Street_Num] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_PO_Box] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_City] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_County] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_State_Code] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Postal_Code] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Country_Code] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Latitude] [numeric] (32, 16) NULL,
[Invc_Cust_Longitude] [numeric] (32, 16) NULL,
[Invc_Cust_Tax_Group_Name] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Payment_Mode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Credit_Rating] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Daly_Customer_Number] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Daly_Company_Number] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Invc_Cust_Daly_Flag] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dim_DC_Ledger_Location_key] [int] NOT NULL,
[DC_Location_Data_Area_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DC_Location_Number] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DC_Location_Name] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_Ship_From_DC_Location_key] [int] NOT NULL,
[Ship_From_Invent_Location_ID] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_From_Location_Name] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_From_DC_Location] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_From_Store_Name] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_From_Store_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_From_Street_Address] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_From_City] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_From_State_Code] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_From_Country_Code] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_From_Postal_Code] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_From_Phone_Num] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_From_Latitude] [float] NOT NULL,
[Ship_From_Longitude] [float] NOT NULL,
[Ship_From_Daly_Warehouse_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ship_From_Daly_Flag] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_Sales_Rep_key] [int] NOT NULL,
[Sales_Rep_Employee_ID] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Rep_Employee_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Rep_Email_Address] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Rep_Default_Location] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Rep_Job_Title] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Rep_Daly_Employee_ID] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Sales_Rep_Daly_Company_Number] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Sales_Rep_Daly_Flag] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dim_Sales_Rep_Manager_key] [int] NOT NULL,
[Sales_Rep_Manager_Employee_ID] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Rep_Manager_Employee_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Rep_Manager_Email_Address] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Rep_Manager_Default_Location] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Rep_Manager_Job_Title] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Rep_Manager_Daly_Employee_ID] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Sales_Rep_Manager_Daly_Company_Number] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Sales_Rep_Manager_Daly_Flag] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dim_Store_key] [int] NOT NULL,
[Store_Invent_Location_ID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Store_Name] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Store_DC_Location] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Store_ID] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Store_Description] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Store_District_Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Store_Street_Name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Store_Country_Code] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Store_Postal_Code] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Store_City] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Store_State_Code] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Store_Phone_Number] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Store_Daly_Warehouse_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Store_Daly_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dim_POS_key] [int] NOT NULL,
[POS_Store_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POS_Till_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POS_Store_Name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POS_Till_Description] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_AX_Inven_Tran_Type_key] [int] NOT NULL,
[AX_Inventory_Transaction_Type] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dim_Shipping_Address_key] [int] NOT NULL,
[Shipping_Name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Shipping_Address] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Shipping_Street_Number] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Shipping_Street_Name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Shipping_PO_Box] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Shipping_City] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Shipping_State_Code] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Shipping_County] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Shipping_Country_Code] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Shipping_Postal_Code] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_Billing_Address_key] [int] NOT NULL,
[Billing_Name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing_Address] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing_Street_Number] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing_Street_Name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing_PO_Box] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing_City] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing_State_Code] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing_County] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing_Country_Code] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Billing_Postal_Code] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_Company_key] [int] NOT NULL,
[Data_Area_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Company_Name] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Daly_Company_Number] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Daly_Company_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dim_Sales_Date_key] [int] NOT NULL,
[Sales_MM_DD_YYYY] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_YYYY_MM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_YYYY_MM_DD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Formatted_Date] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Calendar_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Calendar_Year_No] [int] NULL,
[Sales_Calendar_Year_Month_No] [int] NULL,
[Sales_Calendar_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Calendar_Month_Number] [int] NULL,
[Sales_Month_Name] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Month_Name_With_Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Month_Abbreviation] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Season_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Season_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Season_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Season_Month] [int] NULL,
[Sales_Season_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Season_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Season_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Season_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Season_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Season_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Player_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Player_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Player_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Player_Month] [int] NULL,
[Sales_Player_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Player_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Player_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Player_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Player_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Player_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_League_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_League_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_League_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_League_Month] [int] NULL,
[Sales_League_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_League_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_League_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_League_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_League_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_League_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Week] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Week_Order_By] [int] NULL,
[Sales_Week_Number] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Day_Of_Month_Number] [int] NULL,
[Sales_Day_Of_Week_Number] [int] NULL,
[Sales_Day_Name] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Year_Week] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Current_Date_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Current_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Current_Year_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Season_Day_Number] [int] NULL,
[Sales_Calendar_Day_Number] [int] NULL,
[Sales_League_Day_Number] [int] NULL,
[Sales_Player_Day_Number] [int] NULL,
[Sales_Retail_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Retail_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Retail_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Retail_Month] [int] NULL,
[Sales_Retail_Day_Number] [int] NULL,
[Sales_Retail_Day_In_Month_Number] [int] NULL,
[Sales_Retail_Week_Number] [int] NULL,
[Sales_Retail_Month_Name] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Retail_Month_Name_With_Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Retail_Month_Abbreviation] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Retail_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Retail_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Retail_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Retail_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Retail_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Retail_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Game_Day] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Game_Day_Weekend] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Game_Day_Indicator] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_First_Day_Of_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Last_Day_Of_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_Sales_Time_key] [int] NOT NULL,
[Sales_Time_Minute] [int] NOT NULL,
[Sales_Hour_Of_Day_24] [int] NOT NULL,
[Sales_Hour_Of_Day_12] [int] NOT NULL,
[Sales_Formatted_Hour] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Sales_Formatted_Time] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Sales_Formatted_Time24] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Sales_Minute_Of_Day] [int] NOT NULL,
[Sales_Minute_Of_Hour] [int] NOT NULL,
[Sales_AM_PM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Sales_Time_Stamp] [smalldatetime] NOT NULL,
[Sales_Interval_15_Minute] [smallint] NULL,
[Sales_Interval_30_Minute] [smallint] NULL,
[dim_Status_Date_key] [int] NOT NULL,
[Status_MM_DD_YYYY] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_YYYY_MM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_YYYY_MM_DD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Formatted_Date] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Calendar_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Calendar_Year_No] [int] NULL,
[Status_Calendar_Year_Month_No] [int] NULL,
[Status_Calendar_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Calendar_Month_Number] [int] NULL,
[Status_Month_Name] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Month_Name_With_Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Month_Abbreviation] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Season_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Season_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Season_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Season_Month] [int] NULL,
[Status_Season_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Season_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Season_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Season_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Season_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Season_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Player_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Player_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Player_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Player_Month] [int] NULL,
[Status_Player_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Player_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Player_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Player_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Player_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Player_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_League_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_League_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_League_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_League_Month] [int] NULL,
[Status_League_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_League_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_League_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_League_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_League_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_League_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Week] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Week_Order_By] [int] NULL,
[Status_Week_Number] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Day_Of_Month_Number] [int] NULL,
[Status_Day_Of_Week_Number] [int] NULL,
[Status_Day_Name] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Year_Week] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Current_Date_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Current_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Current_Year_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Season_Day_Number] [int] NULL,
[Status_Calendar_Day_Number] [int] NULL,
[Status_League_Day_Number] [int] NULL,
[Status_Player_Day_Number] [int] NULL,
[Status_Retail_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Retail_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Retail_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Retail_Month] [int] NULL,
[Status_Retail_Day_Number] [int] NULL,
[Status_Retail_Day_In_Month_Number] [int] NULL,
[Status_Retail_Week_Number] [int] NULL,
[Status_Retail_Month_Name] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Retail_Month_Name_With_Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Retail_Month_Abbreviation] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Retail_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Retail_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Retail_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Retail_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Retail_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Retail_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Game_Day] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Game_Day_Weekend] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Game_Day_Indicator] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_First_Day_Of_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Status_Last_Day_Of_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_Invoice_Date_key] [int] NOT NULL,
[Invoice_MM_DD_YYYY] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_YYYY_MM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_YYYY_MM_DD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Formatted_Date] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Calendar_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Calendar_Year_No] [int] NULL,
[Invoice_Calendar_Year_Month_No] [int] NULL,
[Invoice_Calendar_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Calendar_Month_Number] [int] NULL,
[Invoice_Month_Name] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Month_Name_With_Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Month_Abbreviation] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Season_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Season_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Season_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Season_Month] [int] NULL,
[Invoice_Season_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Season_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Season_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Season_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Season_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Season_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Player_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Player_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Player_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Player_Month] [int] NULL,
[Invoice_Player_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Player_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Player_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Player_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Player_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Player_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_League_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_League_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_League_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_League_Month] [int] NULL,
[Invoice_League_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_League_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_League_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_League_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_League_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_League_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Week] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Week_Order_By] [int] NULL,
[Invoice_Week_Number] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Day_Of_Month_Number] [int] NULL,
[Invoice_Day_Of_Week_Number] [int] NULL,
[Invoice_Day_Name] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Year_Week] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Current_Date_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Current_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Current_Year_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Season_Day_Number] [int] NULL,
[Invoice_Calendar_Day_Number] [int] NULL,
[Invoice_League_Day_Number] [int] NULL,
[Invoice_Player_Day_Number] [int] NULL,
[Invoice_Retail_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Retail_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Retail_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Retail_Month] [int] NULL,
[Invoice_Retail_Day_Number] [int] NULL,
[Invoice_Retail_Day_In_Month_Number] [int] NULL,
[Invoice_Retail_Week_Number] [int] NULL,
[Invoice_Retail_Month_Name] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Retail_Month_Name_With_Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Retail_Month_Abbreviation] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Retail_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Retail_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Retail_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Retail_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Retail_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Retail_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Game_Day] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Game_Day_Weekend] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Game_Day_Indicator] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_First_Day_Of_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invoice_Last_Day_Of_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_Order_Date_key] [int] NOT NULL,
[Order_MM_DD_YYYY] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_YYYY_MM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_YYYY_MM_DD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Formatted_Date] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Calendar_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Calendar_Year_No] [int] NULL,
[Order_Calendar_Year_Month_No] [int] NULL,
[Order_Calendar_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Calendar_Month_Number] [int] NULL,
[Order_Month_Name] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Month_Name_With_Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Month_Abbreviation] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Season_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Season_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Season_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Season_Month] [int] NULL,
[Order_Season_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Season_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Season_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Season_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Season_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Season_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Player_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Player_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Player_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Player_Month] [int] NULL,
[Order_Player_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Player_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Player_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Player_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Player_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Player_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_League_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_League_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_League_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_League_Month] [int] NULL,
[Order_League_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_League_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_League_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_League_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_League_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_League_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Week] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Week_Order_By] [int] NULL,
[Order_Week_Number] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Day_Of_Month_Number] [int] NULL,
[Order_Day_Of_Week_Number] [int] NULL,
[Order_Day_Name] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Year_Week] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Current_Date_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Current_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Current_Year_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Season_Day_Number] [int] NULL,
[Order_Calendar_Day_Number] [int] NULL,
[Order_League_Day_Number] [int] NULL,
[Order_Player_Day_Number] [int] NULL,
[Order_Retail_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Retail_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Retail_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Retail_Month] [int] NULL,
[Order_Retail_Day_Number] [int] NULL,
[Order_Retail_Day_In_Month_Number] [int] NULL,
[Order_Retail_Week_Number] [int] NULL,
[Order_Retail_Month_Name] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Retail_Month_Name_With_Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Retail_Month_Abbreviation] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Retail_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Retail_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Retail_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Retail_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Retail_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Retail_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Game_Day] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Game_Day_Weekend] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Game_Day_Indicator] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_First_Day_Of_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Order_Last_Day_Of_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_Requested_Ship_Date_key] [int] NOT NULL,
[Requested_Ship_MM_DD_YYYY] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_YYYY_MM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_YYYY_MM_DD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Formatted_Date] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Calendar_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Calendar_Year_No] [int] NULL,
[Requested_Ship_Calendar_Year_Month_No] [int] NULL,
[Requested_Ship_Calendar_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Calendar_Month_Number] [int] NULL,
[Requested_Ship_Month_Name] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Month_Name_With_Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Month_Abbreviation] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Season_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Season_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Season_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Season_Month] [int] NULL,
[Requested_Ship_Season_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Season_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Season_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Season_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Season_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Season_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Player_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Player_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Player_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Player_Month] [int] NULL,
[Requested_Ship_Player_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Player_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Player_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Player_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Player_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Player_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_League_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_League_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_League_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_League_Month] [int] NULL,
[Requested_Ship_League_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_League_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_League_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_League_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_League_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_League_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Week] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Week_Order_By] [int] NULL,
[Requested_Ship_Week_Number] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Day_Of_Month_Number] [int] NULL,
[Requested_Ship_Day_Of_Week_Number] [int] NULL,
[Requested_Ship_Day_Name] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Year_Week] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Current_Date_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Current_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Current_Year_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Season_Day_Number] [int] NULL,
[Requested_Ship_Calendar_Day_Number] [int] NULL,
[Requested_Ship_League_Day_Number] [int] NULL,
[Requested_Ship_Player_Day_Number] [int] NULL,
[Requested_Ship_Retail_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Retail_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Retail_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Retail_Month] [int] NULL,
[Requested_Ship_Retail_Day_Number] [int] NULL,
[Requested_Ship_Retail_Day_In_Month_Number] [int] NULL,
[Requested_Ship_Retail_Week_Number] [int] NULL,
[Requested_Ship_Retail_Month_Name] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Retail_Month_Name_With_Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Retail_Month_Abbreviation] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Retail_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Retail_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Retail_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Retail_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Retail_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Retail_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Game_Day] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Game_Day_Weekend] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Game_Day_Indicator] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_First_Day_Of_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Requested_Ship_Last_Day_Of_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_Actual_Ship_Date_key] [int] NOT NULL,
[Actual_Ship_MM_DD_YYYY] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_YYYY_MM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_YYYY_MM_DD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Formatted_Date] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Calendar_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Calendar_Year_No] [int] NULL,
[Actual_Ship_Calendar_Year_Month_No] [int] NULL,
[Actual_Ship_Calendar_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Calendar_Month_Number] [int] NULL,
[Actual_Ship_Month_Name] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Month_Name_With_Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Month_Abbreviation] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Fiscal_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Fiscal_Year_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Fiscal_Year_Month] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Fiscal_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Fiscal_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Fiscal_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Fiscal_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Fiscal_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Fiscal_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Fiscal_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Season_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Season_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Season_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Season_Month] [int] NULL,
[Actual_Ship_Season_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Season_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Season_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Season_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Season_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Season_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Player_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Player_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Player_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Player_Month] [int] NULL,
[Actual_Ship_Player_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Player_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Player_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Player_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Player_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Player_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_League_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_League_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_League_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_League_Month] [int] NULL,
[Actual_Ship_League_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_League_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_League_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_League_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_League_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_League_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Week] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Week_Order_By] [int] NULL,
[Actual_Ship_Week_Number] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Day_Of_Month_Number] [int] NULL,
[Actual_Ship_Day_Of_Week_Number] [int] NULL,
[Actual_Ship_Day_Name] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Year_Week] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Current_Date_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Current_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Current_Year_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Season_Day_Number] [int] NULL,
[Actual_Ship_Calendar_Day_Number] [int] NULL,
[Actual_Ship_League_Day_Number] [int] NULL,
[Actual_Ship_Player_Day_Number] [int] NULL,
[Actual_Ship_Fiscal_Day_Number] [int] NULL,
[Actual_Ship_Retail_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Retail_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Retail_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Retail_Month] [int] NULL,
[Actual_Ship_Retail_Day_Number] [int] NULL,
[Actual_Ship_Retail_Day_In_Month_Number] [int] NULL,
[Actual_Ship_Retail_Week_Number] [int] NULL,
[Actual_Ship_Retail_Month_Name] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Retail_Month_Name_With_Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Retail_Month_Abbreviation] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Retail_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Retail_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Retail_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Retail_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Retail_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Retail_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Game_Day] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Game_Day_Weekend] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Game_Day_Indicator] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_First_Day_Of_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Actual_Ship_Last_Day_Of_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_Forecast_Date_key] [int] NOT NULL,
[Forecast_MM_DD_YYYY] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_YYYY_MM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_YYYY_MM_DD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Formatted_Date] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Calendar_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Calendar_Year_No] [int] NULL,
[Forecast_Calendar_Year_Month_No] [int] NULL,
[Forecast_Calendar_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Calendar_Month_Number] [int] NULL,
[Forecast_Month_Name] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Month_Name_With_Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Month_Abbreviation] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Season_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Season_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Season_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Season_Month] [int] NULL,
[Forecast_Season_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Season_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Season_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Season_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Season_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Season_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Player_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Player_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Player_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Player_Month] [int] NULL,
[Forecast_Player_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Player_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Player_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Player_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Player_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Player_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_League_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_League_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_League_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_League_Month] [int] NULL,
[Forecast_League_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_League_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_League_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_League_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_League_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_League_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Week] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Week_Order_By] [int] NULL,
[Forecast_Week_Number] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Day_Of_Month_Number] [int] NULL,
[Forecast_Day_Of_Week_Number] [int] NULL,
[Forecast_Day_Name] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Year_Week] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Current_Date_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Current_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Current_Year_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Season_Day_Number] [int] NULL,
[Forecast_Calendar_Day_Number] [int] NULL,
[Forecast_League_Day_Number] [int] NULL,
[Forecast_Player_Day_Number] [int] NULL,
[Forecast_Retail_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Retail_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Retail_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Retail_Month] [int] NULL,
[Forecast_Retail_Day_Number] [int] NULL,
[Forecast_Retail_Day_In_Month_Number] [int] NULL,
[Forecast_Retail_Week_Number] [int] NULL,
[Forecast_Retail_Month_Name] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Retail_Month_Name_With_Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Retail_Month_Abbreviation] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Retail_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Retail_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Retail_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Retail_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Retail_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Retail_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Game_Day] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Game_Day_Weekend] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Game_Day_Indicator] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_First_Day_Of_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Forecast_Last_Day_Of_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_Cancel_Date_key] [int] NOT NULL,
[Cancel_MM_DD_YYYY] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_YYYY_MM] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_YYYY_MM_DD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Formatted_Date] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Calendar_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Calendar_Year_No] [int] NULL,
[Cancel_Calendar_Year_Month_No] [int] NULL,
[Cancel_Calendar_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Calendar_Month_Number] [int] NULL,
[Cancel_Month_Name] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Month_Name_With_Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Month_Abbreviation] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Season_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Season_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Season_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Season_Month] [int] NULL,
[Cancel_Season_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Season_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Season_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Season_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Season_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Season_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Player_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Player_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Player_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Player_Month] [int] NULL,
[Cancel_Player_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Player_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Player_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Player_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Player_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Player_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_League_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_League_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_League_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_League_Month] [int] NULL,
[Cancel_League_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_League_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_League_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_League_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_League_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_League_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Week] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Week_Order_By] [int] NULL,
[Cancel_Week_Number] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Day_Of_Month_Number] [int] NULL,
[Cancel_Day_Of_Week_Number] [int] NULL,
[Cancel_Day_Name] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Year_Week] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Current_Date_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Current_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Current_Year_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Season_Day_Number] [int] NULL,
[Cancel_Calendar_Day_Number] [int] NULL,
[Cancel_League_Day_Number] [int] NULL,
[Cancel_Player_Day_Number] [int] NULL,
[Cancel_Retail_Current_Year] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Retail_Year] [nvarchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Retail_Quarter] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Retail_Month] [int] NULL,
[Cancel_Retail_Day_Number] [int] NULL,
[Cancel_Retail_Day_In_Month_Number] [int] NULL,
[Cancel_Retail_Week_Number] [int] NULL,
[Cancel_Retail_Month_Name] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Retail_Month_Name_With_Year] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Retail_Month_Abbreviation] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Retail_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Retail_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Retail_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Retail_YOY_MTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Retail_YOY_QTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Retail_YOY_YTD] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Game_Day] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Game_Day_Weekend] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Game_Day_Indicator] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_First_Day_Of_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Last_Day_Of_Month_Flag] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[dim_Sales_Order_Status_key] [int] NOT NULL,
[Sales_Order_Status] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Sales_Order_Sub_Status] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dim_Sales_Order_Risk_key] [int] NOT NULL,
[Sales_Order_Risk] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Sales_Order_Risk_Order_By] [int] NOT NULL,
[dim_CancelReason_key] [int] NOT NULL,
[Cancel_Reason_Code] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Cancel_Reason_Description] [nvarchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[System_Name] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[dim_System_key] [int] NOT NULL,
[Sales_Date] [date] NULL,
[Status_Date] [date] NULL,
[Invoice_Date] [date] NULL,
[Order_Date] [date] NULL,
[Requested_Ship_Date] [date] NULL,
[Actual_Ship_Date] [date] NULL,
[Forecast_Date] [date] NULL,
[Cancel_Date] [date] NULL,
[Invent_Trans_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sales_Order_Line_Number] [numeric] (32, 16) NULL,
[Invoice_Line_Number] [int] NULL,
[Cancelled_Units] [bigint] NULL,
[Units] [bigint] NULL,
[Price] [money] NULL,
[Dollars] [money] NULL,
[Line_Discount_Percentage] [float] NULL,
[Line_Discount_Dollars] [money] NULL,
[Order_Discount_Percentage] [float] NULL,
[Order_Discount_Dollars] [money] NULL,
[Average_Cost] [money] NULL,
[Line_Cost] [money] NULL,
[Gross_Margin] [money] NULL,
[Trans_ID] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
