CREATE TABLE [stg].[Sync_temp_ods_SGDW_FactTickets]
(
[ftLocalId] [int] NOT NULL,
[ftHolderCompanyId] [int] NOT NULL,
[ftTicketGuid] [uniqueidentifier] NULL,
[ftTransactIssuerCompanyId] [int] NULL,
[ftTransactNum] [int] NULL,
[ftTransactionGuid] [uniqueidentifier] NULL,
[ftSupplierCompanyId] [int] NULL,
[ftEventGuid] [uniqueidentifier] NULL,
[ftAreaGuid] [uniqueidentifier] NULL,
[ftSeatIdInAreaMap] [int] NULL,
[ftRetailerCompanyId] [int] NULL,
[ftPriceTypeGuid] [uniqueidentifier] NULL,
[ftItemGuid] [uniqueidentifier] NOT NULL,
[ftItemPrice] [money] NULL,
[ftTotalTax] [money] NULL,
[ftTotalTaxIncluded] [money] NULL,
[ftTotalVat] [money] NULL,
[ftTotalVatIncluded] [money] NULL,
[ftTotalCommission] [money] NULL,
[ftTotalDiscount] [money] NULL,
[ftActionSign] [bit] NULL,
[ftTicketStatus] [bit] NULL,
[ftIsReserved] [bit] NULL,
[ftIsComplimentary] [bit] NULL,
[ftShiftGuid] [uniqueidentifier] NULL,
[ftReservationExpiryDate] [datetime] NULL,
[ftExtraFields] [xml] NULL,
[ftSalePointGuid] [uniqueidentifier] NULL,
[ftUserGuid] [uniqueidentifier] NULL,
[ftTillGuid] [uniqueidentifier] NULL,
[ftAssociatedClientGuid] [uniqueidentifier] NULL,
[ftIsAccount] [bit] NULL,
[ftClientGuid] [uniqueidentifier] NULL,
[ftRecoAccountGuid] [uniqueidentifier] NULL,
[ftActualDate] [datetime] NULL,
[ftBusinessDate] [datetime] NULL,
[ftTransactionNote] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ftTicketNote] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ftApplicationChannel] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ftSaleModeGuid] [uniqueidentifier] NULL,
[ftForwardTransactionGuid] [uniqueidentifier] NULL,
[ftBackwardTransactionGuid] [uniqueidentifier] NULL,
[ftRelCommision] [money] NULL,
[ftBusinessCategoryGuid] [uniqueidentifier] NULL,
[ftConfirmationDate] [datetime] NULL,
[ftPriceLevelGuid] [uniqueidentifier] NULL,
[ftOnBehalfOfAccountGuid] [uniqueidentifier] NULL,
[ftSubscriptionInstanceGuid] [uniqueidentifier] NULL,
[ftRestrictionGuid] [uniqueidentifier] NULL,
[ftTicketNumber] [int] NULL,
[ftTotalCommissionIncluded] [money] NULL,
[ftIsPrinted] [bit] NULL,
[ftPrintingHistoryGuid] [uniqueidentifier] NULL,
[ftRelationName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ftRelatedItemGuid] [uniqueidentifier] NULL,
[ftPriceEffectivenessEnum] [int] NULL,
[ftIsEffectiveInSubscription] [bit] NULL,
[ftSubscriberTicketTypeEnum] [int] NULL,
[ftCouponItemGuid] [uniqueidentifier] NULL,
[ftCouponDefinitionGuid] [uniqueidentifier] NULL,
[ftIsModifiedReservation] [bit] NULL,
[ftSubsidizedByAccountId] [uniqueidentifier] NULL,
[ftRelatedSubscriptionInstanceGuid] [uniqueidentifier] NULL,
[ftRoleInSubscriptionEnum] [int] NULL,
[ftWorthInSubscriptionBalance] [float] NULL,
[ftSellerBranchGuid] [uniqueidentifier] NULL,
[ftGroupOrderGuid] [uniqueidentifier] NULL,
[ftGroupOrderId] [int] NULL,
[ftPrintCount] [int] NULL,
[ftIsScanned] [bit] NULL,
[ftIsForResale] [bit] NULL,
[ftIsResale] [bit] NULL,
[ftIsResold] [bit] NULL,
[ftContinuedByTicketGuid] [uniqueidentifier] NULL,
[ftContinuedByActionEnum] [int] NULL,
[ftBenefitPackageElementGuid] [uniqueidentifier] NULL,
[ftBenefitMembershipGuid] [uniqueidentifier] NULL,
[ftIsTurnback] [bit] NULL,
[ftPrintMethod] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ftPrintMethodData] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ftLastVersionGuid] [uniqueidentifier] NULL,
[ETL_Sync_Id] [int] NOT NULL IDENTITY(1, 1)
)
GO
ALTER TABLE [stg].[Sync_temp_ods_SGDW_FactTickets] ADD CONSTRAINT [PK__Sync_tem__19364FD2C5395DA7] PRIMARY KEY CLUSTERED  ([ETL_Sync_Id])
GO
