CREATE TABLE [stg].[SG_FactTicketSales]
(
[FactTicketSalesID] [int] NOT NULL IDENTITY(1, 1),
[ETL__SSID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ETL__SSID_SG_event_guid] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL__SSID_SG_sector_guid] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL__SSID_SG_seat_guid] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL__SSID_SG_client_guid] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL__SSID_SG_pricetype_guid] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimDateId] [int] NOT NULL,
[DimTimeId] [int] NOT NULL,
[DimTicketCustomerId] [bigint] NOT NULL,
[DimArenaId] [int] NOT NULL,
[DimSeasonId] [int] NOT NULL,
[DimItemId] [int] NOT NULL,
[DimEventId] [int] NOT NULL,
[DimPlanId] [int] NOT NULL,
[DimPriceLevelId] [int] NOT NULL,
[DimPriceTypeId] [int] NOT NULL,
[DimPriceCodeId] [int] NOT NULL,
[DimLedgerId] [int] NOT NULL,
[DimSeatId_Start] [int] NOT NULL,
[DimSeatStatusId] [int] NOT NULL,
[DimRepId] [int] NOT NULL,
[DimSalesCodeId] [int] NOT NULL,
[DimPromoId] [int] NOT NULL,
[DimEventZoneId] [int] NOT NULL,
[DimOfferId] [int] NOT NULL,
[DimPlanTypeId] [int] NOT NULL,
[DimTicketTypeId] [int] NOT NULL,
[DimSeatTypeId] [int] NOT NULL,
[DimTicketClassId] [int] NOT NULL,
[OrderDate] [datetime] NULL,
[CreatedBy] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UpdatedBy] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedDate] [datetime] NULL,
[UpdatedDate] [datetime] NULL,
[QtySeat] [int] NULL,
[QtySeatFSE] [decimal] (18, 6) NULL,
[QtySeatRenewable] [int] NULL,
[RevenueTicket] [decimal] (18, 6) NULL,
[RevenueFees] [decimal] (18, 6) NULL,
[RevenueSurcharge] [decimal] (18, 6) NULL,
[RevenueTax] [decimal] (18, 6) NULL,
[RevenueTotal] [decimal] (18, 6) NULL,
[FullPrice] [decimal] (18, 6) NULL,
[Discount] [decimal] (18, 6) NULL,
[PaidStatus] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PaidAmount] [decimal] (18, 6) NULL,
[OwedAmount] [decimal] (18, 6) NULL,
[PaymentDateFirst] [datetime] NULL,
[PaymentDateLast] [datetime] NULL,
[IsSold] [bit] NULL,
[IsReserved] [bit] NULL,
[IsReturned] [bit] NULL,
[IsPremium] [bit] NULL,
[IsDiscount] [bit] NULL,
[IsComp] [bit] NULL,
[IsHost] [bit] NULL,
[IsPlan] [bit] NULL,
[IsPartial] [bit] NULL,
[IsSingleEvent] [bit] NULL,
[IsGroup] [bit] NULL,
[IsBroker] [bit] NULL,
[IsRenewal] [bit] NULL,
[IsExpanded] [bit] NULL,
[IsAutoRenewalNextSeason] [bit] NULL,
[SG_TransactNum] [bigint] NULL,
[SG_TicketStatus] [int] NULL,
[SG_IsReserved] [bit] NULL,
[SG_TicketNumber] [int] NULL,
[SG_IsPrinted] [bit] NULL,
[SG_IsModifiedReservation] [bit] NULL,
[Custom_Int_1] [int] NULL,
[Custom_Int_2] [int] NULL,
[Custom_Int_3] [int] NULL,
[Custom_Int_4] [int] NULL,
[Custom_Int_5] [int] NULL,
[Custom_Dec_1] [decimal] (18, 6) NULL,
[Custom_Dec_2] [decimal] (18, 6) NULL,
[Custom_Dec_3] [decimal] (18, 6) NULL,
[Custom_Dec_4] [decimal] (18, 6) NULL,
[Custom_Dec_5] [decimal] (18, 6) NULL,
[Custom_DateTime_1] [datetime] NULL,
[Custom_DateTime_2] [datetime] NULL,
[Custom_DateTime_3] [datetime] NULL,
[Custom_DateTime_4] [datetime] NULL,
[Custom_DateTime_5] [datetime] NULL,
[Custom_Bit_1] [bit] NULL,
[Custom_Bit_2] [bit] NULL,
[Custom_Bit_3] [bit] NULL,
[Custom_Bit_4] [bit] NULL,
[Custom_Bit_5] [bit] NULL,
[Custom_nVarChar_1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom_nVarChar_2] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom_nVarChar_3] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom_nVarChar_4] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Custom_nVarChar_5] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
