CREATE TABLE [stg].[SG_FactHeldSeats]
(
[ETL__ID] [int] NOT NULL IDENTITY(1, 1),
[ETL__SSID] [varchar] (51) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL__SSID_SG_ticket_guid] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL__SSID_SG_event_guid] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL__SSID_SG_sector_guid] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL__SSID_SG_seat_guid] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL__SSID_SG_pricetype_guid] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimDateId] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimTimeId] [int] NULL,
[DimTicketCustomerId] [bigint] NULL,
[DimArenaId] [int] NULL,
[DimSeasonId] [int] NULL,
[DimItemId] [int] NULL,
[DimEventId] [int] NULL,
[DimPlanId] [int] NULL,
[DimPriceLevelId] [int] NULL,
[DimPriceTypeId] [int] NULL,
[DimPriceCodeId] [int] NULL,
[DimLedgerId] [int] NULL,
[DimSeatId_Start] [int] NULL,
[DimSeatStatusId] [int] NULL,
[DimRepId] [int] NULL,
[DimSalesCodeId] [int] NULL,
[DimPlanTypeId] [int] NULL,
[DimTicketTypeId] [int] NULL,
[DimSeatTypeId] [int] NULL,
[DimTicketClassId] [int] NULL,
[IsReserved] [bit] NULL,
[HeldDateTime] [datetime] NULL,
[QtySeat] [int] NULL,
[SubTotal] [decimal] (20, 6) NULL,
[Fees] [decimal] (18, 6) NULL,
[Taxes] [decimal] (18, 6) NULL,
[Total] [decimal] (18, 6) NULL,
[SG_TransactNum] [int] NULL,
[SG_TicketStatus] [bit] NULL,
[SG_IsReserved] [bit] NULL,
[SG_TicketNumber] [int] NULL,
[SG_IsPrinted] [bit] NULL,
[SG_IsModifiedReservation] [bit] NULL,
[SG_IsLocked] [bit] NULL,
[SG_IsSold] [bit] NULL
)
GO
